### ISSUE TITLE
Not all translations are available

### ISSUE THREAD

**Issue by brendan-pike** [Bakual/BibleLinkXT#1]
I've just installed thus plugin but found I was unable to select the translation I desired which was Tree of Life Version (TLV)

Let me know if I can provide more info.

Thanks

**Comment by Bakual** [comment]
@brendan-pike I've updated the list of available bibles. That should fix the issue. Can you test if it fixes it for you?
You can just download the repo here and install the zip in your Joomla (https://github.com/Bakual/BibleLinkXT/archive/refs/heads/master.zip)

**Comment by brendan-pike** [comment]
Thanks, it now works although I noticed that the 'Living Bible' is listed twice.

**Comment by Bakual** [comment]
Oops. That's why it's good to have a second pair eyes.
